import type { Site } from "./interface";
import * as img from "./assets";

export const sites: Site[] = [
  {
    id: 1,
    name: "Upwork",
    url: "https://www.upwork.com/",
    description:
      "Millions of freelance gigs for virtual assistants, writers, & more.",
    categories: ["design", "writing", "development", "freelance"],
    image: img.upwork,
  },
  {
    id: 2,
    name: "Fiverr",
    url: "https://www.fiverr.com/",
    description: "Start small with 55+ gigs and build your portfolio.",
    categories: ["design", "writing", "development", "freelance"],
    image: img.fiverr,
  },
  {
    id: 3,
    name: "Toptal",
    url: "https://www.toptal.com/",
    description: "High-paying freelance gigs with 0% commission cuts.",
    categories: ["development", "freelance"],
    image: img.toptal,
  },
  {
    id: 4,
    name: "99designs",
    url: "https://99designs.com/",
    categories: ["design", "freelance"],
    image: img.Design99,
  },
  {
    id: 5,
    name: "Dribbble",
    url: "https://dribbble.com/jobs",
    description: "Remote gigs for animators, designers, and product creators.",
    categories: ["design", "freelance"],
    image: img.Dribble,
  },
  {
    id: 6,
    name: "Contently",
    url: "https://contently.com/",
    categories: ["writing", "freelance"],
    image: img.Contently,
  },
  {
    id: 7,
    name: "Guru",
    url: "https://www.guru.com/",
    categories: ["design", "development", "freelance"],
    image: img.guru,
  },
  {
    id: 8,
    name: "WriterAccess",
    url: "https://www.writeraccess.com/",
    categories: ["writing", "freelance"],
    image: img.writeAccess,
  },
  {
    id: 9,
    name: "Freelancer.com",
    url: "https://www.freelancer.com",
    categories: ["design", "writing", "development", "freelance"],
    image: img.freelance,
  },
  {
    id: 10,
    name: "PeoplePerHour",
    url: "https://www.peopleperhour.com",
    categories: ["design", "writing", "development", "freelance"],
    image: img.peoplePerHour,
  },
  {
    id: 11,
    name: "ProBlogger Jobs",
    url: "https://problogger.com/jobs/",
    categories: ["writing", "freelance"],
    image: img.proBlogger,
  },
  {
    id: 12,
    name: "We Work Remotely",
    url: "https://weworkremotely.com/",
    description: "Find 130,000+ remote jobs in tech, design, and more!",
    categories: ["design", "development"],
    image: img.weWorkRemotely,
  },
  {
    id: 13,
    name: "FlexJobs",
    url: "https://www.flexjobs.com",
    description: "Discover 50+ remote job categories with 100,000+ listings.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 14,
    name: "Arc",
    url: "https://arc.dev",
    description: "AI-matched remote developer jobs & internships worldwide.",
    categories: ["development"],
    image: "",
  },
  {
    id: 15,
    name: "Jobspresso",
    url: "https://jobspresso.co",
    description: "Freelance and full-time jobs across 5+ industries.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 16,
    name: "RemoteCo",
    url: "https://remote.co",
    description: "Remote work resources and job listings across industries.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 17,
    name: "JustRemote",
    url: "https://justremote.co",
    description: "Access hidden remote jobs with PowerSearch for $6/month.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 18,
    name: "Virtual Vocations",
    url: "https://www.virtualvocations.com",
    description: "Find thousands of telecommuting jobs & exclusive resources.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 19,
    name: "Remoteve",
    url: "https://remotive.io",
    description: "Bi-monthly updates of remote jobs in 8+ categories.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 20,
    name: "Skip the Drive",
    url: "https://www.skipthedrive.com",
    description: "Resources & remote jobs without the gridlock.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 21,
    name: "Pangian",
    url: "https://pangian.com",
    description: "Join the fastest-growing global remote job community.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 22,
    name: "Working Nomads",
    url: "https://www.workingnomads.co",
    description: "Curated remote job emails daily or weekly.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 23,
    name: "PowerToFly",
    url: "https://powertofly.com",
    description:
      "Development-focused job board connecting diverse professionals globally.",
    categories: ["development"],
    image: "",
  },
  {
    id: 24,
    name: "Remote OK",
    url: "https://remoteok.com",
    description:
      "Remote job board with listings in Development, design, and more.",
    categories: ["development", "design"],
    image: "",
  },
  {
    id: 25,
    name: "LandingJobs",
    url: "https://landing.jobs",
    description: "Remote jobs filtered by flexibility and commuting distance.",
    categories: ["development"],
    image: "",
  },
  {
    id: 26,
    name: "Career Vault",
    url: "https://careervault.io",
    description: "Search 200+ fresh remote jobs added daily.",
    categories: ["design", "writing", "development"],
    image: "",
  },
  {
    id: 27,
    name: "Authentic Jobs",
    url: "https://authenticjobs.com",
    description: "Remote Development and design jobs from trusted companies.",
    categories: ["development", "design"],
    image: "",
  },
  {
    id: 28,
    name: "Wellfound",
    url: "https://wellfound.com",
    description: "Explore 100s of remote startup jobs worldwide.",
    categories: ["development"],
    image: "",
  },
  {
    id: 29,
    name: "Designhill",
    url: "https://www.designhill.com",
    description: "Join creative contests & connect with global clients.",
    categories: ["design"],
    image: "",
  },
  {
    id: 30,
    name: "FreelancerMap",
    url: "https://www.freelancermap.com",
    description: "Global IT freelance jobs with 11,000+ live listings.",
    categories: ["development"],
    image: "",
  },
  {
    id: 31,
    name: "Gun",
    url: "https://gun.io",
    description: "Freelance for developers—keep 100% of what you earn.",
    categories: ["development"],
    image: "",
  },
  {
    id: 32,
    name: "Behance",
    url: "https://www.behance.net",
    description: "Showcase your portfolio and land design gigs globally.",
    categories: ["design"],
    image: "",
  },
];
